# This is a basic workflow to help you get started with Actions

name: Version Operatorhub

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      operator-image-tag:
        description: 'Tag of the ibmcom/starter-kit-operator image eg 0.0.0'     
        required: true
        default: 1.1.1
      old-operator-version:
        description: 'version of operator to upgrade from must be an existing dir in community-operators/starter-kit-operator eg 0.0.0'     
        required: true
        default: 0.2.0
      new-operator-version:
        description: 'version of operator to upgrade to eg 0.0.1'     
        required: true
        default: 0.2.1
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: master

      # Runs a single command using the runners shell
      - name: Create Dir and Replace Values and Commit
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          set -x
          
          mkdir $GITHUB_WORKSPACE/../fork
          cd $GITHUB_WORKSPACE/..
          
          git clone https://github.com/operator-framework/community-operators/
          cd community-operators/community-operators/starter-kit-operator
          
          sudo snap install yq
          
          rm -rf ${{ github.event.inputs.new-operator-version }}
          cp -r ${{ github.event.inputs.old-operator-version }} ${{ github.event.inputs.new-operator-version }}

          mv ${{ github.event.inputs.new-operator-version }}/starter-kit-operator.v${{ github.event.inputs.old-operator-version }}.clusterserviceversion.yaml ${{ github.event.inputs.new-operator-version }}/starter-kit-operator.v${{ github.event.inputs.new-operator-version }}.clusterserviceversion.yaml

          yq write --inplace starter-kit-operator.package.yaml channels[0].currentCSV starter-kit-operator.v${{ github.event.inputs.new-operator-version }}

          SKIT_CSV=${{ github.event.inputs.new-operator-version }}/starter-kit-operator.v${{ github.event.inputs.new-operator-version }}.clusterserviceversion.yaml

          yq write --inplace $SKIT_CSV metadata.annotations.containerImage ibmcom/starter-kit-operator:${{ github.event.inputs.operator-image-tag }}
          yq write --inplace $SKIT_CSV metadata.name starter-kit-operator.v${{ github.event.inputs.new-operator-version }}
          yq write --inplace $SKIT_CSV spec.install.spec.deployments[0].spec.template.spec.containers[0].image ibmcom/starter-kit-operator:${{ github.event.inputs.operator-image-tag }}
          yq write --inplace $SKIT_CSV spec.replaces starter-kit-operator.v${{ github.event.inputs.old-operator-version }}
          yq write --inplace $SKIT_CSV spec.version ${{ github.event.inputs.new-operator-version }}

          git config user.name github-actions
          git config user.email github-actions@github.com
          
          git add .
          git commit -m "Update IBM Starter Kit operator to v${{ github.event.inputs.new-operator-version }}"
          
          git remote add fork https://github.com/nfstein/community-operators
          git push -u fork create-${{ github.event.inputs.new-operator-version }}

          echo Open a PR against the parent repo here: https://github.com/operator-framework/community-operators/pulls

